###########################################################################
- name: Manage some installation and services
###########################################################################
  hosts: 127.0.0.1
  tasks:
    - name: Installing Apache and PHP
      become: yes
      ansible.builtin.apt:
        name: apache2, php
        state: present
        update_cache: yes

    - name: Starting and enabling Apache in boot
      become: yes
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - apache2

###########################################################################
- name: Sparse checkout https://github.com/MariMendM/devops-sandbox/Project006/website
###########################################################################
  hosts: 127.0.0.1
  vars:
    checkout_folder: /home/ubuntu/devops-sandbox
    folder_to_clone: Project006/website
    folder_repo: https://github.com/MariMendM/devops-sandbox

  tasks:
    - name: Persisting variables for next plays in playbook
      ansible.builtin.set_fact:
        checkout_folder: "{{ checkout_folder }}"
        folder_to_clone: "{{ folder_to_clone }}"

    - name: Deleting sparse checkout folder
      ansible.builtin.file:
        path: "{{ checkout_folder }}"
        state: absent

    - name: Creating sparse checkout folder
      ansible.builtin.file:
        path: "{{ checkout_folder }}"
        state: directory

    - name: Git init, git remote add and sparse checkout true
      shell: |
        git init
        git remote add -f origin {{ folder_repo }}
        git config core.sparseCheckout true
      args:
        chdir: "{{ checkout_folder }}"

    - name: Creating sparse checkout file with name of folder to be cloned
      ansible.builtin.lineinfile:
        path: "{{ checkout_folder }}/.git/info/sparse-checkout"
        line: "{{ folder_to_clone }}"
        create: yes

    - name: Git pull folder from repo
      shell: git pull origin master
      args:
        chdir: "{{ checkout_folder }}"

###########################################################################
- name: Copy website to Apache folder
###########################################################################
  hosts: 127.0.0.1
  tasks:
    - name: Copying
      become: yes
      ansible.builtin.copy:
        src: "{{ checkout_folder }}/{{ folder_to_clone }}/" #last slash determines that only the content shall be copied, not the folder itself
        dest: /var/www/html

###########################################################################
- name: Signal the Auto Scaling Group Lifecycle Hook with CONTINUE
###########################################################################
  hosts: 127.0.0.1
  vars:
    AWSEnvironmentName: p006
    AWSRegion: region
  tasks:
    - name: Sending complete-lifecycle-action signal to active hook
      #lifecycle-hook-name/auto-scaling-group-name shall be precisely the same configured in EC2AutoScalingGroup of cloudformation.yml
      shell: aws autoscaling complete-lifecycle-action --lifecycle-action-result CONTINUE \
             --instance-id $(curl http://instance-data/latest/meta-data/instance-id) \
             --lifecycle-hook-name {{ AWSEnvironmentName }}-sclng-grp-lfhook --auto-scaling-group-name {{ AWSEnvironmentName }}-sclng-grp \
             --region {{ AWSRegion }}
