###########################################################################
- name: Manage Apache
###########################################################################
  hosts: 127.0.0.1
  tasks:
    - name: Installing Apache
      become: yes
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Starting and enabling Apache in boot
      become: yes
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - apache2