- hosts: 127.0.0.1
  tasks:
    - name: Installing Apache
      become: yes
      apt:
        name: apache2
        state: present
        update_cache: yes
    - service:
        name: Configuring service "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - apache2